tests: tests.o linked-list.o
	gcc -o tests tests.o linked-list.o

tests.o: tests.c 
	 gcc -o tests.o -c tests.c 

linked-list.o: linked-list.c
	gcc -o linked-list.o -c linked-list.c

clean:
	rm -rf *.o
	rm -f tests
 







